--
-- PostgreSQL database dump
--

\restrict aCplbYN6Kd9kQfK2IYuTkLYmZFv7OePJvBg0pbYn1X4WZ5AC0DCoMGxPvhB7qyU

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(200) NOT NULL,
    birthday date,
    company_id uuid
);


ALTER TABLE public.accounts_customuser OWNER TO postgres;

--
-- Name: accounts_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_customuser_groups OWNER TO postgres;

--
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_customuser_user_permissions OWNER TO postgres;

--
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cart; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_cart (
    id bigint NOT NULL,
    status character varying(12) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    company_id uuid NOT NULL,
    user_id bigint NOT NULL,
    nfe_id character varying(255),
    nfe_message text,
    nfe_status character varying(20) NOT NULL,
    nfe_url character varying(200),
    payment_method character varying(20) NOT NULL
);


ALTER TABLE public.cart_cart OWNER TO postgres;

--
-- Name: cart_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cartitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    item_id bigint NOT NULL,
    CONSTRAINT cart_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.cart_cartitem OWNER TO postgres;

--
-- Name: cart_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_application; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_application (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.catalog_application OWNER TO postgres;

--
-- Name: catalog_application_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_conversion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_conversion (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.catalog_conversion OWNER TO postgres;

--
-- Name: catalog_conversion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_conversion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_conversion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_globalitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_globalitem (
    id bigint NOT NULL,
    identity character varying(50) NOT NULL,
    normalized_description text
);


ALTER TABLE public.catalog_globalitem OWNER TO postgres;

--
-- Name: catalog_globalitem_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_globalitem_applications (
    id bigint NOT NULL,
    globalitem_id bigint NOT NULL,
    application_id bigint NOT NULL
);


ALTER TABLE public.catalog_globalitem_applications OWNER TO postgres;

--
-- Name: catalog_globalitem_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_globalitem_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_globalitem_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_globalitem_conversions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_globalitem_conversions (
    id bigint NOT NULL,
    globalitem_id bigint NOT NULL,
    conversion_id bigint NOT NULL
);


ALTER TABLE public.catalog_globalitem_conversions OWNER TO postgres;

--
-- Name: catalog_globalitem_conversions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_globalitem_conversions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_globalitem_conversions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_globalitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_globalitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_globalitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_globalitem_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_globalitem_tags (
    id bigint NOT NULL,
    globalitem_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.catalog_globalitem_tags OWNER TO postgres;

--
-- Name: catalog_globalitem_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_globalitem_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_globalitem_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_item; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_item (
    id bigint NOT NULL,
    description text NOT NULL,
    company_id uuid NOT NULL,
    global_item_id bigint,
    is_active boolean NOT NULL
);


ALTER TABLE public.catalog_item OWNER TO postgres;

--
-- Name: catalog_item_conversions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_item_conversions (
    id bigint NOT NULL,
    item_id bigint NOT NULL,
    conversion_id bigint NOT NULL
);


ALTER TABLE public.catalog_item_conversions OWNER TO postgres;

--
-- Name: catalog_item_conversions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_item_conversions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_item_conversions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_item_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_item_tags (
    id bigint NOT NULL,
    item_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


ALTER TABLE public.catalog_item_tags OWNER TO postgres;

--
-- Name: catalog_item_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_item_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_item_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_itemapplication; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_itemapplication (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    application_id bigint NOT NULL,
    item_id bigint NOT NULL,
    CONSTRAINT catalog_itemapplication_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.catalog_itemapplication OWNER TO postgres;

--
-- Name: catalog_itemapplication_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_itemapplication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_itemapplication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalog_tag; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.catalog_tag (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.catalog_tag OWNER TO postgres;

--
-- Name: catalog_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.catalog_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalog_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_rest_passwordreset_resetpasswordtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_rest_passwordreset_resetpasswordtoken (
    created_at timestamp with time zone NOT NULL,
    key character varying(64) NOT NULL,
    ip_address inet,
    user_agent character varying(512) NOT NULL,
    user_id bigint NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.django_rest_passwordreset_resetpasswordtoken OWNER TO postgres;

--
-- Name: django_rest_passwordreset_resetpasswordtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_rest_passwordreset_resetpasswordtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_rest_passwordreset_resetpasswordtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: inventory_inventoryitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_inventoryitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    cost_price numeric(10,2) NOT NULL,
    sell_price numeric(10,2) NOT NULL,
    item_id bigint NOT NULL
);


ALTER TABLE public.inventory_inventoryitem OWNER TO postgres;

--
-- Name: inventory_inventoryitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_inventoryitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inventoryitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knox_authtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.knox_authtoken (
    digest character varying(128) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    expiry timestamp with time zone,
    token_key character varying(25) NOT NULL
);


ALTER TABLE public.knox_authtoken OWNER TO postgres;

--
-- Name: multicompany_company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multicompany_company (
    id uuid NOT NULL,
    razao_social character varying(255) NOT NULL,
    nome_fantasia character varying(255) NOT NULL,
    cnpj character varying(18) NOT NULL,
    ie character varying(32) NOT NULL,
    regime_tributario character varying(12) NOT NULL,
    status character varying(12) NOT NULL,
    logradouro character varying(255) NOT NULL,
    numero character varying(32) NOT NULL,
    complemento character varying(128) NOT NULL,
    bairro character varying(128) NOT NULL,
    cidade character varying(128) NOT NULL,
    uf character varying(2) NOT NULL,
    cep character varying(9) NOT NULL,
    ibge_municipio character varying(7) NOT NULL,
    codigo_pais character varying(4) NOT NULL,
    nome_pais character varying(50) NOT NULL,
    pais character varying(3) NOT NULL,
    telefone character varying(32) NOT NULL,
    email character varying(254) NOT NULL,
    ambiente character varying(12) NOT NULL,
    credenciais_api jsonb,
    csc character varying(64) NOT NULL,
    csc_id_token character varying(8) NOT NULL,
    moeda character varying(8) NOT NULL,
    timezone_str character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.multicompany_company OWNER TO postgres;

--
-- Data for Name: accounts_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_customuser (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, birthday, company_id) FROM stdin;
1	pbkdf2_sha256$1000000$D8nSBSGcbxNfYhEhZtzuye$fOk1aP7xMxtdT3H3aXHI3NLCSu5lEPlL7rndF0HxE8o=	2026-04-09 17:49:24.373456+00	t			t	t	2026-04-08 16:50:32.328599+00	adalton@mzpartsmanager.com	\N	\N
\.


--
-- Data for Name: accounts_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Password Reset Token	6	add_resetpasswordtoken
22	Can change Password Reset Token	6	change_resetpasswordtoken
23	Can delete Password Reset Token	6	delete_resetpasswordtoken
24	Can view Password Reset Token	6	view_resetpasswordtoken
25	Can add auth token	7	add_authtoken
26	Can change auth token	7	change_authtoken
27	Can delete auth token	7	delete_authtoken
28	Can view auth token	7	view_authtoken
29	Can add user	8	add_customuser
30	Can change user	8	change_customuser
31	Can delete user	8	delete_customuser
32	Can view user	8	view_customuser
33	Can add Empresa	9	add_company
34	Can change Empresa	9	change_company
35	Can delete Empresa	9	delete_company
36	Can view Empresa	9	view_company
37	Can add application	10	add_application
38	Can change application	10	change_application
39	Can delete application	10	delete_application
40	Can view application	10	view_application
41	Can add conversion	11	add_conversion
42	Can change conversion	11	change_conversion
43	Can delete conversion	11	delete_conversion
44	Can view conversion	11	view_conversion
45	Can add tag	12	add_tag
46	Can change tag	12	change_tag
47	Can delete tag	12	delete_tag
48	Can view tag	12	view_tag
49	Can add global item	13	add_globalitem
50	Can change global item	13	change_globalitem
51	Can delete global item	13	delete_globalitem
52	Can view global item	13	view_globalitem
53	Can add item	14	add_item
54	Can change item	14	change_item
55	Can delete item	14	delete_item
56	Can view item	14	view_item
57	Can add item application	15	add_itemapplication
58	Can change item application	15	change_itemapplication
59	Can delete item application	15	delete_itemapplication
60	Can view item application	15	view_itemapplication
61	Can add inventory item	16	add_inventoryitem
62	Can change inventory item	16	change_inventoryitem
63	Can delete inventory item	16	delete_inventoryitem
64	Can view inventory item	16	view_inventoryitem
65	Can add cart	17	add_cart
66	Can change cart	17	change_cart
67	Can delete cart	17	delete_cart
68	Can view cart	17	view_cart
69	Can add cart item	18	add_cartitem
70	Can change cart item	18	change_cartitem
71	Can delete cart item	18	delete_cartitem
72	Can view cart item	18	view_cartitem
\.


--
-- Data for Name: cart_cart; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_cart (id, status, created_at, updated_at, company_id, user_id, nfe_id, nfe_message, nfe_status, nfe_url, payment_method) FROM stdin;
\.


--
-- Data for Name: cart_cartitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cart_cartitem (id, quantity, cart_id, item_id) FROM stdin;
\.


--
-- Data for Name: catalog_application; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_application (id, name) FROM stdin;
\.


--
-- Data for Name: catalog_conversion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_conversion (id, name) FROM stdin;
\.


--
-- Data for Name: catalog_globalitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_globalitem (id, identity, normalized_description) FROM stdin;
\.


--
-- Data for Name: catalog_globalitem_applications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_globalitem_applications (id, globalitem_id, application_id) FROM stdin;
\.


--
-- Data for Name: catalog_globalitem_conversions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_globalitem_conversions (id, globalitem_id, conversion_id) FROM stdin;
\.


--
-- Data for Name: catalog_globalitem_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_globalitem_tags (id, globalitem_id, tag_id) FROM stdin;
\.


--
-- Data for Name: catalog_item; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_item (id, description, company_id, global_item_id, is_active) FROM stdin;
\.


--
-- Data for Name: catalog_item_conversions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_item_conversions (id, item_id, conversion_id) FROM stdin;
\.


--
-- Data for Name: catalog_item_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_item_tags (id, item_id, tag_id) FROM stdin;
\.


--
-- Data for Name: catalog_itemapplication; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_itemapplication (id, "order", application_id, item_id) FROM stdin;
\.


--
-- Data for Name: catalog_tag; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.catalog_tag (id, name) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	django_rest_passwordreset	resetpasswordtoken
7	knox	authtoken
8	accounts	customuser
9	multicompany	company
10	catalog	application
11	catalog	conversion
12	catalog	tag
13	catalog	globalitem
14	catalog	item
15	catalog	itemapplication
16	inventory	inventoryitem
17	cart	cart
18	cart	cartitem
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	multicompany	0001_initial	2026-04-08 16:41:14.917171+00
2	contenttypes	0001_initial	2026-04-08 16:41:14.939036+00
3	contenttypes	0002_remove_content_type_name	2026-04-08 16:41:14.960871+00
4	auth	0001_initial	2026-04-08 16:41:15.036335+00
5	auth	0002_alter_permission_name_max_length	2026-04-08 16:41:15.04632+00
6	auth	0003_alter_user_email_max_length	2026-04-08 16:41:15.053012+00
7	auth	0004_alter_user_username_opts	2026-04-08 16:41:15.06371+00
8	auth	0005_alter_user_last_login_null	2026-04-08 16:41:15.072014+00
9	auth	0006_require_contenttypes_0002	2026-04-08 16:41:15.075579+00
10	auth	0007_alter_validators_add_error_messages	2026-04-08 16:41:15.085091+00
11	auth	0008_alter_user_username_max_length	2026-04-08 16:41:15.098149+00
12	auth	0009_alter_user_last_name_max_length	2026-04-08 16:41:15.111971+00
13	auth	0010_alter_group_name_max_length	2026-04-08 16:41:15.130928+00
14	auth	0011_update_proxy_permissions	2026-04-08 16:41:15.14857+00
15	auth	0012_alter_user_first_name_max_length	2026-04-08 16:41:15.156817+00
16	accounts	0001_initial	2026-04-08 16:41:15.25693+00
17	accounts	0002_alter_customuser_managers_remove_customuser_username	2026-04-08 16:41:15.27566+00
18	accounts	0003_customuser_company	2026-04-08 16:41:15.304862+00
19	admin	0001_initial	2026-04-08 16:41:15.356749+00
20	admin	0002_logentry_remove_auto_add	2026-04-08 16:41:15.374189+00
21	admin	0003_logentry_add_action_flag_choices	2026-04-08 16:41:15.3903+00
22	catalog	0001_initial	2026-04-08 16:41:15.635478+00
23	catalog	0002_alter_application_name_alter_conversion_name_and_more	2026-04-08 16:41:15.716696+00
24	catalog	0003_item_is_active	2026-04-08 16:41:15.734894+00
25	catalog	0004_remove_item_applications_itemapplication	2026-04-08 16:41:15.785282+00
26	catalog	0005_item_applications	2026-04-08 16:41:15.804758+00
27	cart	0001_initial	2026-04-08 16:41:15.924898+00
28	cart	0002_cart_nfe_id_cart_nfe_message_cart_nfe_status_and_more	2026-04-08 16:41:15.975822+00
29	django_rest_passwordreset	0001_initial	2026-04-08 16:41:16.013076+00
30	django_rest_passwordreset	0002_pk_migration	2026-04-08 16:41:16.105555+00
31	django_rest_passwordreset	0003_allow_blank_and_null_fields	2026-04-08 16:41:16.125109+00
32	django_rest_passwordreset	0004_alter_resetpasswordtoken_user_agent	2026-04-08 16:41:16.14045+00
33	inventory	0001_initial	2026-04-08 16:41:16.145374+00
34	inventory	0002_initial	2026-04-08 16:41:16.179132+00
35	knox	0001_initial	2026-04-08 16:41:16.224187+00
36	knox	0002_auto_20150916_1425	2026-04-08 16:41:16.285458+00
37	knox	0003_auto_20150916_1526	2026-04-08 16:41:16.317799+00
38	knox	0004_authtoken_expires	2026-04-08 16:41:16.338039+00
39	knox	0005_authtoken_token_key	2026-04-08 16:41:16.371963+00
40	knox	0006_auto_20160818_0932	2026-04-08 16:41:16.420134+00
41	knox	0007_auto_20190111_0542	2026-04-08 16:41:16.437228+00
42	knox	0008_remove_authtoken_salt	2026-04-08 16:41:16.450582+00
43	knox	0009_extend_authtoken_field	2026-04-08 16:41:16.473928+00
44	sessions	0001_initial	2026-04-08 16:41:16.503166+00
\.


--
-- Data for Name: django_rest_passwordreset_resetpasswordtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_rest_passwordreset_resetpasswordtoken (created_at, key, ip_address, user_agent, user_id, id) FROM stdin;
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
02ippntb5nnxfywmssdpqmpnzpgz3j1g	.eJxVjEEOwiAQRe_C2hAolCku3XsGMjOAVA0kpV0Z765NutDtf-_9lwi4rSVsPS1hjuIstDj9boT8SHUH8Y711iS3ui4zyV2RB-3y2mJ6Xg7376BgL98aHVk3eAY2U_aOQY_TqDIxUgJwWXvm5BQrshTzYCIqDxnAGucNxiTeH_LBOHM:1wAtVM:Ag_8f9vYucZpWEiK0njVygfhgS4tuuvldQD__kRjzOc	2026-04-23 17:49:24.377522+00
\.


--
-- Data for Name: inventory_inventoryitem; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory_inventoryitem (id, quantity, cost_price, sell_price, item_id) FROM stdin;
\.


--
-- Data for Name: knox_authtoken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.knox_authtoken (digest, created, user_id, expiry, token_key) FROM stdin;
\.


--
-- Data for Name: multicompany_company; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.multicompany_company (id, razao_social, nome_fantasia, cnpj, ie, regime_tributario, status, logradouro, numero, complemento, bairro, cidade, uf, cep, ibge_municipio, codigo_pais, nome_pais, pais, telefone, email, ambiente, credenciais_api, csc, csc_id_token, moeda, timezone_str, created_at, updated_at) FROM stdin;
\.


--
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_customuser_groups_id_seq', 1, false);


--
-- Name: accounts_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_customuser_id_seq', 1, true);


--
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_customuser_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: cart_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_cart_id_seq', 1, false);


--
-- Name: cart_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_cartitem_id_seq', 1, false);


--
-- Name: catalog_application_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_application_id_seq', 1, false);


--
-- Name: catalog_conversion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_conversion_id_seq', 1, false);


--
-- Name: catalog_globalitem_applications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_globalitem_applications_id_seq', 1, false);


--
-- Name: catalog_globalitem_conversions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_globalitem_conversions_id_seq', 1, false);


--
-- Name: catalog_globalitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_globalitem_id_seq', 1, false);


--
-- Name: catalog_globalitem_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_globalitem_tags_id_seq', 1, false);


--
-- Name: catalog_item_conversions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_item_conversions_id_seq', 1, false);


--
-- Name: catalog_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_item_id_seq', 1, false);


--
-- Name: catalog_item_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_item_tags_id_seq', 1, false);


--
-- Name: catalog_itemapplication_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_itemapplication_id_seq', 1, false);


--
-- Name: catalog_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.catalog_tag_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 44, true);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_rest_passwordreset_resetpasswordtoken_id_seq', 1, false);


--
-- Name: inventory_inventoryitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_inventoryitem_id_seq', 1, false);


--
-- Name: accounts_customuser accounts_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_email_key UNIQUE (email);


--
-- Name: accounts_customuser_groups accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq UNIQUE (customuser_id, group_id);


--
-- Name: accounts_customuser_groups accounts_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser accounts_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser_user_permissions accounts_customuser_user_customuser_id_permission_9632a709_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser_user_customuser_id_permission_9632a709_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: accounts_customuser_user_permissions accounts_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: cart_cart cart_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_pkey PRIMARY KEY (id);


--
-- Name: cart_cartitem cart_cartitem_cart_id_item_id_44741058_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_cart_id_item_id_44741058_uniq UNIQUE (cart_id, item_id);


--
-- Name: cart_cartitem cart_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_pkey PRIMARY KEY (id);


--
-- Name: catalog_application catalog_application_name_83f2c972_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_application
    ADD CONSTRAINT catalog_application_name_83f2c972_uniq UNIQUE (name);


--
-- Name: catalog_application catalog_application_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_application
    ADD CONSTRAINT catalog_application_pkey PRIMARY KEY (id);


--
-- Name: catalog_conversion catalog_conversion_name_cbe83292_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_conversion
    ADD CONSTRAINT catalog_conversion_name_cbe83292_uniq UNIQUE (name);


--
-- Name: catalog_conversion catalog_conversion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_conversion
    ADD CONSTRAINT catalog_conversion_pkey PRIMARY KEY (id);


--
-- Name: catalog_globalitem_applications catalog_globalitem_appli_globalitem_id_applicatio_000cfb4c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_applications
    ADD CONSTRAINT catalog_globalitem_appli_globalitem_id_applicatio_000cfb4c_uniq UNIQUE (globalitem_id, application_id);


--
-- Name: catalog_globalitem_applications catalog_globalitem_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_applications
    ADD CONSTRAINT catalog_globalitem_applications_pkey PRIMARY KEY (id);


--
-- Name: catalog_globalitem_conversions catalog_globalitem_conve_globalitem_id_conversion_36f2fdc5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_conversions
    ADD CONSTRAINT catalog_globalitem_conve_globalitem_id_conversion_36f2fdc5_uniq UNIQUE (globalitem_id, conversion_id);


--
-- Name: catalog_globalitem_conversions catalog_globalitem_conversions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_conversions
    ADD CONSTRAINT catalog_globalitem_conversions_pkey PRIMARY KEY (id);


--
-- Name: catalog_globalitem catalog_globalitem_identity_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem
    ADD CONSTRAINT catalog_globalitem_identity_key UNIQUE (identity);


--
-- Name: catalog_globalitem catalog_globalitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem
    ADD CONSTRAINT catalog_globalitem_pkey PRIMARY KEY (id);


--
-- Name: catalog_globalitem_tags catalog_globalitem_tags_globalitem_id_tag_id_67ce380e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_tags
    ADD CONSTRAINT catalog_globalitem_tags_globalitem_id_tag_id_67ce380e_uniq UNIQUE (globalitem_id, tag_id);


--
-- Name: catalog_globalitem_tags catalog_globalitem_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_tags
    ADD CONSTRAINT catalog_globalitem_tags_pkey PRIMARY KEY (id);


--
-- Name: catalog_item_conversions catalog_item_conversions_item_id_conversion_id_4b971317_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item_conversions
    ADD CONSTRAINT catalog_item_conversions_item_id_conversion_id_4b971317_uniq UNIQUE (item_id, conversion_id);


--
-- Name: catalog_item_conversions catalog_item_conversions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item_conversions
    ADD CONSTRAINT catalog_item_conversions_pkey PRIMARY KEY (id);


--
-- Name: catalog_item catalog_item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item
    ADD CONSTRAINT catalog_item_pkey PRIMARY KEY (id);


--
-- Name: catalog_item_tags catalog_item_tags_item_id_tag_id_31c4b3a2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item_tags
    ADD CONSTRAINT catalog_item_tags_item_id_tag_id_31c4b3a2_uniq UNIQUE (item_id, tag_id);


--
-- Name: catalog_item_tags catalog_item_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item_tags
    ADD CONSTRAINT catalog_item_tags_pkey PRIMARY KEY (id);


--
-- Name: catalog_itemapplication catalog_itemapplication_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_itemapplication
    ADD CONSTRAINT catalog_itemapplication_pkey PRIMARY KEY (id);


--
-- Name: catalog_tag catalog_tag_name_c2802f4e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_tag
    ADD CONSTRAINT catalog_tag_name_c2802f4e_uniq UNIQUE (name);


--
-- Name: catalog_tag catalog_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_tag
    ADD CONSTRAINT catalog_tag_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_passwordreset_resetpasswordtoken_key_f1b65873_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_passwordreset_resetpasswordtoken_key_f1b65873_uniq UNIQUE (key);


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_passwordreset_resetpasswordtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_passwordreset_resetpasswordtoken_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: inventory_inventoryitem inventory_inventoryitem_item_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_inventoryitem
    ADD CONSTRAINT inventory_inventoryitem_item_id_key UNIQUE (item_id);


--
-- Name: inventory_inventoryitem inventory_inventoryitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_inventoryitem
    ADD CONSTRAINT inventory_inventoryitem_pkey PRIMARY KEY (id);


--
-- Name: knox_authtoken knox_authtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.knox_authtoken
    ADD CONSTRAINT knox_authtoken_pkey PRIMARY KEY (digest);


--
-- Name: multicompany_company multicompany_company_cnpj_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multicompany_company
    ADD CONSTRAINT multicompany_company_cnpj_key UNIQUE (cnpj);


--
-- Name: multicompany_company multicompany_company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multicompany_company
    ADD CONSTRAINT multicompany_company_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser_company_id_963babd7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_customuser_company_id_963babd7 ON public.accounts_customuser USING btree (company_id);


--
-- Name: accounts_customuser_email_4fd8e7ce_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_customuser_email_4fd8e7ce_like ON public.accounts_customuser USING btree (email varchar_pattern_ops);


--
-- Name: accounts_customuser_groups_customuser_id_bc55088e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_customuser_groups_customuser_id_bc55088e ON public.accounts_customuser_groups USING btree (customuser_id);


--
-- Name: accounts_customuser_groups_group_id_86ba5f9e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_customuser_groups_group_id_86ba5f9e ON public.accounts_customuser_groups USING btree (group_id);


--
-- Name: accounts_customuser_user_permissions_customuser_id_0deaefae; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_customuser_user_permissions_customuser_id_0deaefae ON public.accounts_customuser_user_permissions USING btree (customuser_id);


--
-- Name: accounts_customuser_user_permissions_permission_id_aea3d0e5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_customuser_user_permissions_permission_id_aea3d0e5 ON public.accounts_customuser_user_permissions USING btree (permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: cart_cart_company_id_a28f8a1e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cart_company_id_a28f8a1e ON public.cart_cart USING btree (company_id);


--
-- Name: cart_cart_user_id_9b4220b9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cart_user_id_9b4220b9 ON public.cart_cart USING btree (user_id);


--
-- Name: cart_cartitem_cart_id_370ad265; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cartitem_cart_id_370ad265 ON public.cart_cartitem USING btree (cart_id);


--
-- Name: cart_cartitem_item_id_f315a26e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cart_cartitem_item_id_f315a26e ON public.cart_cartitem USING btree (item_id);


--
-- Name: catalog_application_name_83f2c972_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_application_name_83f2c972_like ON public.catalog_application USING btree (name varchar_pattern_ops);


--
-- Name: catalog_conversion_name_cbe83292_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_conversion_name_cbe83292_like ON public.catalog_conversion USING btree (name varchar_pattern_ops);


--
-- Name: catalog_globalitem_applications_application_id_5e42dfe9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_globalitem_applications_application_id_5e42dfe9 ON public.catalog_globalitem_applications USING btree (application_id);


--
-- Name: catalog_globalitem_applications_globalitem_id_9d558731; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_globalitem_applications_globalitem_id_9d558731 ON public.catalog_globalitem_applications USING btree (globalitem_id);


--
-- Name: catalog_globalitem_conversions_conversion_id_e7baf71e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_globalitem_conversions_conversion_id_e7baf71e ON public.catalog_globalitem_conversions USING btree (conversion_id);


--
-- Name: catalog_globalitem_conversions_globalitem_id_c940711d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_globalitem_conversions_globalitem_id_c940711d ON public.catalog_globalitem_conversions USING btree (globalitem_id);


--
-- Name: catalog_globalitem_identity_d99f3c4b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_globalitem_identity_d99f3c4b_like ON public.catalog_globalitem USING btree (identity varchar_pattern_ops);


--
-- Name: catalog_globalitem_tags_globalitem_id_31c70998; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_globalitem_tags_globalitem_id_31c70998 ON public.catalog_globalitem_tags USING btree (globalitem_id);


--
-- Name: catalog_globalitem_tags_tag_id_816fdbf5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_globalitem_tags_tag_id_816fdbf5 ON public.catalog_globalitem_tags USING btree (tag_id);


--
-- Name: catalog_item_company_id_acd7f5a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_item_company_id_acd7f5a2 ON public.catalog_item USING btree (company_id);


--
-- Name: catalog_item_conversions_conversion_id_0e446cd3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_item_conversions_conversion_id_0e446cd3 ON public.catalog_item_conversions USING btree (conversion_id);


--
-- Name: catalog_item_conversions_item_id_9886ffb3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_item_conversions_item_id_9886ffb3 ON public.catalog_item_conversions USING btree (item_id);


--
-- Name: catalog_item_global_item_id_a15f8799; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_item_global_item_id_a15f8799 ON public.catalog_item USING btree (global_item_id);


--
-- Name: catalog_item_tags_item_id_341300c1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_item_tags_item_id_341300c1 ON public.catalog_item_tags USING btree (item_id);


--
-- Name: catalog_item_tags_tag_id_1f721563; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_item_tags_tag_id_1f721563 ON public.catalog_item_tags USING btree (tag_id);


--
-- Name: catalog_itemapplication_application_id_2f3adbff; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_itemapplication_application_id_2f3adbff ON public.catalog_itemapplication USING btree (application_id);


--
-- Name: catalog_itemapplication_item_id_4e20e7d5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_itemapplication_item_id_4e20e7d5 ON public.catalog_itemapplication USING btree (item_id);


--
-- Name: catalog_tag_name_c2802f4e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX catalog_tag_name_c2802f4e_like ON public.catalog_tag USING btree (name varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_key_f1b65873_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_rest_passwordreset_resetpasswordtoken_key_f1b65873_like ON public.django_rest_passwordreset_resetpasswordtoken USING btree (key varchar_pattern_ops);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_user_id_e8015b11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_rest_passwordreset_resetpasswordtoken_user_id_e8015b11 ON public.django_rest_passwordreset_resetpasswordtoken USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: knox_authtoken_digest_188c7e77_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX knox_authtoken_digest_188c7e77_like ON public.knox_authtoken USING btree (digest varchar_pattern_ops);


--
-- Name: knox_authtoken_token_key_8f4f7d47; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX knox_authtoken_token_key_8f4f7d47 ON public.knox_authtoken USING btree (token_key);


--
-- Name: knox_authtoken_token_key_8f4f7d47_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX knox_authtoken_token_key_8f4f7d47_like ON public.knox_authtoken USING btree (token_key varchar_pattern_ops);


--
-- Name: knox_authtoken_user_id_e5a5d899; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX knox_authtoken_user_id_e5a5d899 ON public.knox_authtoken USING btree (user_id);


--
-- Name: multicompany_company_cnpj_f7f974cd_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX multicompany_company_cnpj_f7f974cd_like ON public.multicompany_company USING btree (cnpj varchar_pattern_ops);


--
-- Name: accounts_customuser_user_permissions accounts_customuser__customuser_id_0deaefae_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser__customuser_id_0deaefae_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_groups accounts_customuser__customuser_id_bc55088e_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser__customuser_id_bc55088e_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_user_permissions accounts_customuser__permission_id_aea3d0e5_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser__permission_id_aea3d0e5_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser accounts_customuser_company_id_963babd7_fk_multicomp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_company_id_963babd7_fk_multicomp FOREIGN KEY (company_id) REFERENCES public.multicompany_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_groups accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cart cart_cart_company_id_a28f8a1e_fk_multicompany_company_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_company_id_a28f8a1e_fk_multicompany_company_id FOREIGN KEY (company_id) REFERENCES public.multicompany_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cart cart_cart_user_id_9b4220b9_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_9b4220b9_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_cart_id_370ad265_fk_cart_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_cart_id_370ad265_fk_cart_cart_id FOREIGN KEY (cart_id) REFERENCES public.cart_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_item_id_f315a26e_fk_catalog_item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_item_id_f315a26e_fk_catalog_item_id FOREIGN KEY (item_id) REFERENCES public.catalog_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_globalitem_applications catalog_globalitem_a_application_id_5e42dfe9_fk_catalog_a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_applications
    ADD CONSTRAINT catalog_globalitem_a_application_id_5e42dfe9_fk_catalog_a FOREIGN KEY (application_id) REFERENCES public.catalog_application(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_globalitem_applications catalog_globalitem_a_globalitem_id_9d558731_fk_catalog_g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_applications
    ADD CONSTRAINT catalog_globalitem_a_globalitem_id_9d558731_fk_catalog_g FOREIGN KEY (globalitem_id) REFERENCES public.catalog_globalitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_globalitem_conversions catalog_globalitem_c_conversion_id_e7baf71e_fk_catalog_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_conversions
    ADD CONSTRAINT catalog_globalitem_c_conversion_id_e7baf71e_fk_catalog_c FOREIGN KEY (conversion_id) REFERENCES public.catalog_conversion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_globalitem_conversions catalog_globalitem_c_globalitem_id_c940711d_fk_catalog_g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_conversions
    ADD CONSTRAINT catalog_globalitem_c_globalitem_id_c940711d_fk_catalog_g FOREIGN KEY (globalitem_id) REFERENCES public.catalog_globalitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_globalitem_tags catalog_globalitem_t_globalitem_id_31c70998_fk_catalog_g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_tags
    ADD CONSTRAINT catalog_globalitem_t_globalitem_id_31c70998_fk_catalog_g FOREIGN KEY (globalitem_id) REFERENCES public.catalog_globalitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_globalitem_tags catalog_globalitem_tags_tag_id_816fdbf5_fk_catalog_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_globalitem_tags
    ADD CONSTRAINT catalog_globalitem_tags_tag_id_816fdbf5_fk_catalog_tag_id FOREIGN KEY (tag_id) REFERENCES public.catalog_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_item catalog_item_company_id_acd7f5a2_fk_multicompany_company_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item
    ADD CONSTRAINT catalog_item_company_id_acd7f5a2_fk_multicompany_company_id FOREIGN KEY (company_id) REFERENCES public.multicompany_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_item_conversions catalog_item_convers_conversion_id_0e446cd3_fk_catalog_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item_conversions
    ADD CONSTRAINT catalog_item_convers_conversion_id_0e446cd3_fk_catalog_c FOREIGN KEY (conversion_id) REFERENCES public.catalog_conversion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_item_conversions catalog_item_conversions_item_id_9886ffb3_fk_catalog_item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item_conversions
    ADD CONSTRAINT catalog_item_conversions_item_id_9886ffb3_fk_catalog_item_id FOREIGN KEY (item_id) REFERENCES public.catalog_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_item catalog_item_global_item_id_a15f8799_fk_catalog_globalitem_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item
    ADD CONSTRAINT catalog_item_global_item_id_a15f8799_fk_catalog_globalitem_id FOREIGN KEY (global_item_id) REFERENCES public.catalog_globalitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_item_tags catalog_item_tags_item_id_341300c1_fk_catalog_item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item_tags
    ADD CONSTRAINT catalog_item_tags_item_id_341300c1_fk_catalog_item_id FOREIGN KEY (item_id) REFERENCES public.catalog_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_item_tags catalog_item_tags_tag_id_1f721563_fk_catalog_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_item_tags
    ADD CONSTRAINT catalog_item_tags_tag_id_1f721563_fk_catalog_tag_id FOREIGN KEY (tag_id) REFERENCES public.catalog_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_itemapplication catalog_itemapplicat_application_id_2f3adbff_fk_catalog_a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_itemapplication
    ADD CONSTRAINT catalog_itemapplicat_application_id_2f3adbff_fk_catalog_a FOREIGN KEY (application_id) REFERENCES public.catalog_application(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalog_itemapplication catalog_itemapplication_item_id_4e20e7d5_fk_catalog_item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.catalog_itemapplication
    ADD CONSTRAINT catalog_itemapplication_item_id_4e20e7d5_fk_catalog_item_id FOREIGN KEY (item_id) REFERENCES public.catalog_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_password_user_id_e8015b11_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_password_user_id_e8015b11_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inventory_inventoryitem inventory_inventoryitem_item_id_56641115_fk_catalog_item_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_inventoryitem
    ADD CONSTRAINT inventory_inventoryitem_item_id_56641115_fk_catalog_item_id FOREIGN KEY (item_id) REFERENCES public.catalog_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: knox_authtoken knox_authtoken_user_id_e5a5d899_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.knox_authtoken
    ADD CONSTRAINT knox_authtoken_user_id_e5a5d899_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict aCplbYN6Kd9kQfK2IYuTkLYmZFv7OePJvBg0pbYn1X4WZ5AC0DCoMGxPvhB7qyU

