# Generated by Django 5.2.9 on 2026-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='nfe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='nfe_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='nfe_status',
            field=models.CharField(choices=[('none', 'Não Emitida'), ('processing', 'Processando'), ('approved', 'Aprovada'), ('error', 'Erro')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='nfe_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito')], default='dinheiro', max_length=20),
        ),
    ]
