# Generated by Django 5.2.8 on 2025-12-16 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multicompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkuSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sku_sequence', to='multicompany.company')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(blank=True, db_index=True, editable=False, max_length=160)),
                ('sku', models.CharField(blank=True, editable=False, max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(choices=[('UN', 'UN'), ('KG', 'KG'), ('LT', 'LT'), ('CX', 'CX')], default='UN', max_length=16)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='multicompany.company')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.itemidentity')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'description'], name='catalog_ite_company_dadc6f_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'sku'), name='uniq_item_company_sku')],
            },
        ),
    ]
