# Generated by Django 5.2.8 on 2025-12-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='skusequence',
            name='company',
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_item_company_sku',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='catalog_ite_company_dadc6f_idx',
        ),
        migrations.RemoveField(
            model_name='item',
            name='active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='identity_key',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity_on_hand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='item',
            name='applications',
            field=models.ManyToManyField(to='catalog.application'),
        ),
        migrations.AddField(
            model_name='globalitem',
            name='applications',
            field=models.ManyToManyField(blank=True, to='catalog.application'),
        ),
        migrations.AddField(
            model_name='item',
            name='global_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.globalitem'),
        ),
        migrations.AddField(
            model_name='globalitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='catalog.tag'),
        ),
        migrations.DeleteModel(
            name='ItemIdentity',
        ),
        migrations.DeleteModel(
            name='SkuSequence',
        ),
    ]
