# Generated by Django 5.2.8 on 2025-12-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_application_globalitem_tag_remove_item_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='applications',
            field=models.ManyToManyField(blank=True, to='catalog.application'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag'),
        ),
    ]
