# Generated by Django 5.2.8 on 2025-12-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_item_applications_alter_item_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='globalitem',
            name='conversion',
            field=models.ManyToManyField(blank=True, to='catalog.conversion'),
        ),
        migrations.AddField(
            model_name='item',
            name='conversions',
            field=models.ManyToManyField(blank=True, to='catalog.conversion'),
        ),
    ]
