# Generated by Django 5.2.8 on 2025-12-27 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_conversion_globalitem_conversion_item_conversions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalitem',
            old_name='conversion',
            new_name='conversions',
        ),
    ]
