# Generated by Django 5.2.9 on 2026-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_item_applications_itemapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='applications',
            field=models.ManyToManyField(blank=True, through='catalog.ItemApplication', to='catalog.application'),
        ),
    ]
