# Generated by Django 5.2.9 on 2026-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_conversion_globalitem_conversions'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalitem',
            name='identity',
            field=models.CharField(default='setup', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalitem',
            name='normalized_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
