# Generated by Django 5.2.9 on 2026-07-01 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_item_applications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemapplication',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='itemapplication',
            unique_together={('item', 'application')},
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/%Y/%m/%d/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.item')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
