# Generated by Django 5.2.8 on 2025-12-16 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('ie', models.CharField(blank=True, default='', max_length=32, verbose_name='Inscrição Estadual')),
                ('regime_tributario', models.CharField(choices=[('simples', 'Simples Nacional'), ('normal', 'Regime Normal')], default='simples', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('suspended', 'Suspensa')], default='pending', max_length=12)),
                ('logradouro', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', max_length=32)),
                ('complemento', models.CharField(blank=True, default='', max_length=128)),
                ('bairro', models.CharField(blank=True, default='', max_length=128)),
                ('cidade', models.CharField(blank=True, default='', max_length=128)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=9)),
                ('ibge_municipio', models.CharField(blank=True, default='', max_length=7)),
                ('codigo_pais', models.CharField(default='1058', max_length=4)),
                ('nome_pais', models.CharField(default='BRASIL', max_length=50)),
                ('pais', models.CharField(default='BRA', max_length=3)),
                ('telefone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=12)),
                ('credenciais_api', models.JSONField(blank=True, help_text='Credenciais fiscais / API (ex: nfe.io)', null=True)),
                ('csc', models.CharField(blank=True, default='', max_length=64)),
                ('csc_id_token', models.CharField(blank=True, default='', max_length=8)),
                ('moeda', models.CharField(default='BRL', max_length=8)),
                ('timezone_str', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
    ]
