# Generated by Django 5.2.9 on 2026-05-11 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_item_applications'),
        ('multicompany', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(choices=[('falta_estoque', 'Falta de estoque'), ('nao_trabalhado', 'Produto não trabalhado'), ('preco_elevado', 'Preço elevado'), ('prazo_entrega', 'Prazo de entrega'), ('marca_qualidade', 'Marca/Qualidade'), ('outro', 'Outro')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('observation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_sales', to='multicompany.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_sales', to='catalog.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
